(in-package #:clinker-transcript/tests)

(defun test-projection-storage ()
  "Test ordered append, detached snapshots, replacement and metadata pruning."
  (let* ((first (user-message-item "first"))
         (second (user-message-item "second"))
         (projection (make-projection :items (vector first)))
         (snapshot (projection-items projection)))
    (setf (gethash first (projection-metadata-table projection ':family)) ':one
          (gethash first (projection-metadata-table projection ':annotation)) nil)
    (check (eq (projection-append projection second) second) "append returns item")
    (check (equal snapshot (list first)) "append does not mutate a snapshot")
    (setf (first snapshot) nil)
    (check (equal (projection-items projection) (list first second))
           "snapshots have independent spines")
    (projection-replace projection (list first))
    (check (eq (gethash first (projection-metadata-table projection ':family)) ':one)
           "replacement retains identity metadata")
    (check (nth-value 1 (gethash first (projection-metadata-table projection ':annotation)))
           "explicit NIL metadata is retained")
    (projection-replace projection (list second))
    (dolist (key '(:family :annotation))
      (check (zerop (hash-table-count (projection-metadata-table projection key)))
             "discarded item metadata is pruned"))
    (let ((cycle (list first)))
      (setf (rest cycle) cycle)
      (dolist (invalid (list cycle (cons first second) "not-items" 42))
        (check (handler-case (progn (projection-replace projection invalid) nil)
                 (projection-error (condition)
                   (eq (projection-error-reason condition) ':invalid-items)))
               "invalid sequence rejected")
        (check (equal (projection-items projection) (list second))
               "invalid replacement is nonmutating")))
    (projection-replace projection nil)
    (loop for index below 10000 do (projection-append projection index))
    (check (equal (projection-items projection) (loop for index below 10000 collect index))
           "large incremental projection retains order")
    (projection-replace projection nil)
    (check (null (projection-items projection)) "empty replacement clears items")))

(defun test-projection-families ()
  "Test private items and portable checkpoint handoffs across model families."
  (let* ((ordinary (user-message-item "portable"))
         (private (json-object "type" "reasoning"))
         (unattributed (json-object "type" "reasoning"))
         (handoff (user-message-item "checkpoint"))
         (projection (make-projection :items (list ordinary private unattributed handoff)))
         (families (projection-metadata-table projection ':family))
         (handoffs (projection-metadata-table projection ':handoff)))
    (setf (gethash private families) ':one
          (gethash handoff handoffs) ':one)
    (dolist (case (list (list ':one (list ordinary private))
                       (list ':two (list ordinary handoff))))
      (check (equal (items-for-family (projection-items projection) (first case)
                                     :item-families families :handoff-families handoffs)
                    (second case))
             "family privacy and handoff selection"))
    (dolist (family '(nil :one))
      (check (equal (items-for-family (list ordinary private) family) (list ordinary))
             "unknown private content is omitted"))))

(defun test-reconciliation-order ()
  "Test call groups, output reordering, orphan positions and missing intents."
  (let* ((first (json-object "type" "function_call" "call_id" "a"))
         (second (json-object "type" "function_call" "call_id" "b"))
         (third (json-object "type" "function_call" "call_id" "c"))
         (first-output (function-call-output-item "a" "one"))
         (second-output (function-call-output-item "b" "two"))
         (orphan (function-call-output-item "old" "legacy"))
         (message (user-message-item "continue"))
         (input (list orphan first second message second-output first-output third))
         (original (copy-list input))
         (plan (reconcile-items input))
         (repairs (reconciliation-repairs plan))
         (third-output (function-call-output-item "c" "unknown")))
    (check (and (= (length repairs) 1)
                (eq (missing-output-repair-call (first repairs)) third)
                (equal (missing-output-repair-call-id (first repairs)) "c"))
           "planning returns a missing output intent")
    (check (equal input original) "planning does not mutate source order")
    (check (equal (reconciliation-items plan :repair-output (lambda (repair)
                                                            (check (eq repair (first repairs))
                                                                   "repair identity")
                                                            third-output))
                  (list orphan first second first-output second-output message third third-output))
           "contiguous calls precede their outputs in call order")
    (check (equal (reconciliation-items
                   (reconcile-items (vector first-output first message)))
                  (list first first-output message))
           "an early output moves after its call")
    (check (equal (reconciliation-items (reconcile-items (list nil message orphan)))
                  (list nil message orphan))
           "unrelated items and orphan outputs retain their positions")
    (check (null (reconciliation-items (reconcile-items nil))) "empty transcript")
    (let ((detached (reconciliation-repairs plan)))
      (setf (first detached) nil)
      (check (eq (first (reconciliation-repairs plan)) (first repairs))
             "repair lists are detached"))))

(defun test-reconciliation-validation ()
  "Test the duplicate/missing identifier matrix and bounded late-result tolerance."
  (let* ((call (json-object "type" "function_call" "call_id" "a"))
         (repair (function-call-output-item "a" "unknown"))
         (ordinary (function-call-output-item "a" "ordinary"))
         (late (function-call-output-item "a" "late"))
         (recognized (lambda (output) (equal (json-get output "output") "unknown"))))
    (dolist (case (list
                  (list (list call call) ':duplicate-call)
                  (list (list call ordinary late) ':duplicate-output)
                  (list (list call repair ordinary late) ':duplicate-output)
                  (list (list repair call ordinary) ':duplicate-output)
                  (list (list repair ordinary) ':duplicate-output)
                  (list (list (json-object "type" "function_call")) ':missing-call-id)
                  (list (list (function-call-output-item "" "x")) ':missing-call-id)
                  (list (list (function-call-output-item 1 "x")) ':missing-call-id)))
      (check (handler-case
                 (progn (reconcile-items (first case) :repaired-output-p recognized) nil)
               (reconciliation-error (condition)
                 (and (eq (projection-error-reason condition) (second case))
                      (member (projection-error-item condition) (first case)))))
             "invalid history has a typed reason and offending item"))
    (check (equal (reconciliation-items
                   (reconcile-items (list call repair ordinary)
                                    :repaired-output-p recognized))
                  (list call repair))
           "exactly one late result is suppressed after a recognized repair")
    (check (handler-case (progn (reconcile-items (list call repair ordinary)) nil)
             (reconciliation-error (condition)
               (equal (reconciliation-error-call-id condition) "a")))
           "repair tolerance requires explicit host recognition")
    (check (eq (validate-function-call call :preceding-items (list ordinary)) call)
           "an existing output does not duplicate a call")
    (check (handler-case (progn (validate-function-call call :preceding-items (vector call)) nil)
             (reconciliation-error (condition)
               (eq (projection-error-reason condition) ':duplicate-call)))
           "live call validation rejects duplicates")
    (check (handler-case (progn (validate-function-call (json-object "type" "function_call")) nil)
             (reconciliation-error (condition)
               (eq (projection-error-reason condition) ':missing-call-id)))
           "live call validation requires an identifier")))

(defun test-reconciliation-recovery ()
  "Test explicit repair resolution, callback failure and retry from published state."
  (let* ((first (json-object "type" "function_call" "call_id" "a"))
         (second (json-object "type" "function_call" "call_id" "b"))
         (durable (list first second))
         (plan (reconcile-items durable)))
    (check (handler-case (progn (reconciliation-items plan) nil)
             (reconciliation-error (condition)
               (eq (projection-error-reason condition) ':missing-output)))
           "unresolved repairs cannot become provider input")
    (check (equal (mapcar (lambda (item) (json-get item "call_id"))
                         (handler-bind
                             ((reconciliation-error
                                (lambda (condition)
                                  (when (eq (projection-error-reason condition) ':missing-output)
                                    (invoke-restart 'clinker-transcript::use-output
                                                    (function-call-output-item
                                                     (reconciliation-error-call-id condition) "unknown"))))))
                           (reconciliation-items plan)))
                  '("a" "b" "a" "b"))
           "USE-OUTPUT resolves missing outputs explicitly")
    (dolist (invalid (list nil first (function-call-output-item "other" "x")))
      (check (handler-case
                 (progn (reconciliation-items plan :repair-output (lambda (intent)
                                                                  (declare (ignore intent))
                                                                  invalid))
                        nil)
               (reconciliation-error (condition)
                 (eq (projection-error-reason condition) ':invalid-repair-output)))
             "repair callbacks must return matching outputs"))
    (check (handler-case
               (progn
                 (reconciliation-items
                  plan :repair-output
                  (lambda (intent)
                    (when (equal (missing-output-repair-call-id intent) "b")
                      (error 'file-error :pathname #P"unpublished"))
                    (let ((output (function-call-output-item
                                   (missing-output-repair-call-id intent) "unknown")))
                      (setf durable (append durable (list output)))
                      output)))
                 nil)
             (file-error () t))
           "publication failure propagates without materializing a replacement")
    (check (= (length (reconciliation-repairs plan)) 2) "the original plan is unchanged")
    (let ((retry (reconcile-items durable)))
      (check (= (length (reconciliation-repairs retry)) 1)
             "replanning discovers only the unpublished repair")
      (setf durable
            (reconciliation-items retry :repair-output
                                  (lambda (intent)
                                    (function-call-output-item
                                     (missing-output-repair-call-id intent) "unknown"))))
      (check (null (reconciliation-repairs (reconcile-items durable)))
             "completed repairs replay without another publication")
      (check (equal (reconciliation-items (reconcile-items durable)) durable)
             "reconciliation is idempotent"))))
